### ISSUE TITLE
docker compose 2.2.1 no key saved in .env

### ISSUE THREAD

**Issue by gimler** [CachetHQ/Cachet#1743]
Before submitting your issue, please make sure that you've checked all of the checkboxes below.

### Your setup

- *What version of Cachet?* v2.2.1
- *What database driver? MySQL? Postgres? SQLite?* postgres
- *What version of PHP?* PHP 7.0.5-3

### Expected behaviour

key is inserted into `.env` file. it works with 2.2.0

### Actual behaviour

no key is inserted into `.env` file

### Steps to reproduce
docker-compose.yml
```
version: "2"

services:
  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./init/nginx-site.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 82:8000
    links:
      - cachet
    volumes_from:
      - cachet
    depends_on:
      - cachet
  postgres:
    image: postgres:9.5
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  cachet:
    image: cachethq/docker:2.2.0
    expose:
      - 9000
    links:
      - postgres:postgres
    environment:
      - DB_DRIVER=pgsql
      - DB_HOST=postgres
      - DB_DATABASE=postgres
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
    volumes:
      - /var/www
    depends_on:
      - postgres
```

```
docker-compose up -d 
docker exec -i docker_cachet_1  php artisan key:generate
docker exec -i docker_cachet_1  cat .env
```
