### ISSUE TITLE
Development using official CachetHQ/Docker image

### ISSUE THREAD

**Issue by xRahul** [CachetHQ/Cachet#2190]
I have outlined the steps here. Let me know what you guys think.

Developing using [CachetHQ/Docker](https://github.com/CachetHQ/Docker):

1.  Clone the official repo of CachetHQ/Docker
```shell
git clone https://github.com/cachethq/Docker.git cachet-docker
cd cachet-docker
git tag -l
git checkout $LATEST_TAG
```
2. Clone the official repo of CachetHQ/Cachet here and do composer install
```shell
git clone https://github.com/CachetHQ/Cachet.git
```
3. Setup the Cachet project
```shell
cd Cachet
composer install
cp ../conf/.env.docker ./.env
cd ..
```
4.Edit the docker-compose.yml file
```yaml
replace 
  build: . 
with 
  image: cachethq/docker

replace
  - /var/www 
with 
  - ./Cachet/:/var/www/html/
```
5.build and run the docker compose
```shell
docker-compose up
```
6. Open new terminal and execute the following commands after getting container name via `docker ps`-
```shell
docker exec -i docker_cachet_1  php artisan key:generate
docker exec -i docker_cachet_1  php artisan app:install
```
Now you have a docker instance running with your local copy of the code.
