### ISSUE TITLE
Tooltips not working correctly in 2.4

### ISSUE THREAD

**Issue by Mintux** [CachetHQ/Cachet#3758]
Hello, in 2.4 branch the tooltips don't have any background. It seems something is broken here.

It's happening in every 2.4 instance. See the demo: https://dev.cachethq.io/
In 2.3 everything is working as expected, see: https://demo.cachethq.io/

Just hover over the parts where you could see the tooltip overlay.
Any quick fix possible? I tried to search this up myself but didn't find the right parts.

**Comment by skyradon** [comment]
Hello again,

I checked the css from the latest 2.3 demo with the current 2.4 demo and my own installation and found the problem with the tooltips not showing correctly. It seem's that some important css rules were removed in 2.4.

Quick fix for any 2.4 installation:

Just import the missing rules back via your custom style in the dashboard:

```css
/* Missing Tooltip Rules */

body.status-page .tooltip .tooltip-inner {
 padding:8px 12px;
 font-size:14px;
 word-wrap:break-word;
}

.tooltip-inner {
 max-width:200px;
 padding:3px 8px;
 color:#fff;
 text-align:center;
 background-color:#333;
 border-radius:3px;
}

.tooltip-arrow {
 position:absolute;
 width:0;
 height:0;
 border-color:transparent;
 border-style:solid;
}

.tooltip.top .tooltip-arrow {
 bottom:0;
 left:50%;
 margin-left:-5px;
 border-width:5px 5px 0;
 border-top-color:#333;
}

.tooltip.top-left .tooltip-arrow {
 right:5px;
}

.tooltip.top-right .tooltip-arrow {
 left:5px;
}

.tooltip.right .tooltip-arrow {
 top:50%;
 left:0;
 margin-top:-5px;
 border-width:5px 5px 5px 0;
 border-right-color:#333;
}

.tooltip.left .tooltip-arrow {
 top:50%;
 right:0;
 margin-top:-5px;
 border-width:5px 0 5px 5px;
 border-left-color:#333;
}

.tooltip.bottom .tooltip-arrow,
.tooltip.bottom-left .tooltip-arrow,
.tooltip.bottom-right .tooltip-arrow {
 border-width:0 5px 5px;
 border-bottom-color:#333;
 top:0;
}

.tooltip.bottom .tooltip-arrow {
 left:50%;
 margin-left:-5px;
}

.tooltip.bottom-left .tooltip-arrow {
 right:5px;
 margin-top:-5px;
}

.tooltip.bottom-right .tooltip-arrow {
 left:5px;
 margin-top:-5px;
}
```
If someone from the team could check this and fix this in the 2.4 branch, it would be fixed for everyone and the fixing part in the custom style area can be removed.

At users: Please don't edit sourcefiles. Wait for a real fix and until then, just use the custom style if you have the same problems. The tooltip will be shown as expected again.

Kind regards.
