### ISSUE TITLE
docker-compose up failing with APP_KEY error

### ISSUE THREAD

**Issue by drewkhoury** [CachetHQ/Cachet#3936]
commit bc48a24dd4485a504e9e7a336f76edfe54299c67 (HEAD -> master, origin/master, origin/HEAD)

docker-compose up

cachet_1    | ERROR: Please set the 'APP_KEY=base64:9G...<omitted>...g1o=' environment variable at runtime or in docker-compose.yml and re-launch

docker-compose.yml

```
  cachet:
    build:
      context: .
      args:
        - cachet_ver=2.4
    ports:
      - 80:8000
    links:
      - postgres:postgres
    environment:
      - APP_KEY=base64:9G...<omitted>...g1o=
      - DB_DRIVER=pgsql
      - DB_HOST=postgres
```
