### ISSUE TITLE
Update docker

### ISSUE THREAD

**Issue by sayem314** [cachethq/cachet#4362]
v2.4.0 is missing in docker image

**Comment by sayem314** [comment]
Any update? @jbrooksuk

**Comment by danimo** [comment]
Is there any way we can help this moving along? I am happy to contribute a github release workflow.

**Comment by jbrooksuk** [comment]
Sorry folks! I've not actually done the Cachet Docker release before. @djdefi did all of that.

If we can get a GitHub workflow going, that'd be great.

**Comment by djdefi** [comment]
Hey @jbrooksuk nice to hear from you!

I used to use this script https://github.com/cachethq/Docker/blob/main/release-helper.sh -- Most of this could be automated in GitHub Actions like https://github.com/docker/build-push-action today instead of doing it via that manual script.

On a new release of Cachet, it comes down to bumping the version here:  https://github.com/cachethq/Docker/blob/e88a87d7a6cd29df8d6d1fb6f05de8678bab1782/Dockerfile#L9 and then creating the relevant GitHub tags/release and pushing the image to Dockerhub etc.

It looks like we have the updates to the Dockerfile and such already in place on main, but I think I lost access to the project before being able to create the relevant tag/release for 2.4.0

Building and running it manually from `main` should work in the interim.

**Comment by danimo** [comment]
See https://github.com/cachethq/Docker/pull/426 for an initial version. Adding support for Docker Hub should be as easy as

```yaml
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }} 
          password: ${{ secrets.DOCKERHUB_TOKEN }}
  ```

And then publish the docker image like the PR does with GHCR. I skipped that mostly because I cannot publish to docker Hub (well, I could setup my own org there, but for now, GHCR was good enough).

Does that help?
